name: Run AddressSanitizer

on:
  push:

jobs:
  run-asan:
    name: '${{ matrix.os }}'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]

    steps:
      - name: Check out repository
        uses: actions/checkout@v2 
        with:
          ref: 6a77f213c4a19d1837c0f478a1adaca1f5c4d543
          
      - name: Build repository 
        run: | 
          export CC=clang
          export CXX=clang++
          export CFLAGS="-fsanitize=address -O1 -fno-omit-frame-pointer -fno-common -fsanitize-recover=address -g"
          export LDFLAGS="-fsanitize=address"
          sed -i 's/^CC\s*=.*/CC = clang/' Makefile && sed -i 's/^CXX\s*=.*/CXX = clang++/' Makefile && sed -i 's/^CFLAGS\s*=.*/& -fsanitize=address -O1 -fno-omit-frame-pointer -fno-common -fsanitize-recover=address -g/' Makefile
          sed -i 's/^LDFLAGS\s*=.*/& -fsanitize=address/' Makefile && sed -i 's/^CPP\s*=.*/CPP = clang -E/' Makefile
          make 

      - name: Install Address Sanitizer dependencies (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get install -y clang-14 libclang-14-dev llvm-14 llvm-14-dev llvm-14-tools llvm-14-linker-tools
      
      - name: Run Google Address Sanitizer
        run: |
          set +e

          DIRECTORY=.

          is_executable() {
            local file="$1"
            if file "$file" | grep -q 'ELF 64-bit'; then
              return 0
            else
              return 1
            fi
          }

          run_with_asan() {
            local executable="$1"
            ASAN_OPTIONS="check_initialization_order=true detect_stack_usr_after_return=true print_stats=true atexit=true strict_string_checks=true usr_odr_indicator=true verbosity=2" timeout 10s "$executable"
            local exit_status=$?
          }

          find "$DIRECTORY" -type f -executable | while read -r file; do
            if is_executable "$file"; then
              run_with_asan "$file"
            fi
          done
