name: Run MemorySanitizer

on:
  push:

jobs:
  run-msan:
    name: '${{ matrix.os }}'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]

    steps:
      - name: Check out repository
        uses: actions/checkout@v2 
        with:
          ref: 6a77f213c4a19d1837c0f478a1adaca1f5c4d543
          
      - name: Build repository 
        run: | 
          export CC=clang
          export CXX=clang++
          export CFLAGS="-fsanitize=memory -fsanitize-memory-track-origins -fPIE -fPIC -g -O2"
          export LDFLAGS="-fsanitize=memory -pie"
          sed -i 's/^CC\s*=.*/CC = clang/' Makefile
          sed -i 's/^CXX\s*=.*/CXX = clang++/' Makefile
          sed -i 's/^CFLAGS\s*=.*/& -fsanitize=memory -fsanitize-memory-track-origins -fPIE -fPIC -g -O2/' Makefile
          sed -i 's/^LDFLAGS\s*=.*/& -fsanitize=memory -pie/' Makefile
          sed -i 's/^CPP\s*=.*/CPP = clang -E/' Makefile
          make 
          
      - name: Install MemorySanitizer dependencies (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get install -y clang-14 libclang-14-dev llvm-14 llvm-14-dev llvm-14-tools llvm-14-linker-tools

      - name: Disable Address Space Randomization
        if: runner.os == 'Linux'
        run: sudo sysctl -w kernel.randomize_va_space=0
      
      - name: Disable swapping 
        if: runner.os == 'Linux' 
        run: sudo swapoff -a
        
      - name: Run Google Memory Sanitizer (source code) (Linux)
        if: runner.os == 'Linux'
        run: |
          #!/bin/bash
          set +e

          mkdir -p memorysan_logs
          DIRECTORY=.

          is_executable() {
            local file="$1"
            if file "$file" | grep -q 'ELF 64-bit'; then
              return 0
            else
              return 1
            fi
          }

          run_with_msan() {
            local executable="$1"
            MSAN_OPTIONS="exit_code=1 verbosity=1 halt_on_error=1 print_stats=1 log_path=./memorysan_logs/$(basename "$executable").txt" timeout 10s "$executable"
            local exit_status=$?
          }

          find "$DIRECTORY" -type f -executable | while read -r file; do
            if is_executable "$file"; then
              run_with_msan "$file"
            fi
          done

      - name: Upload Msan reports
        uses: actions/upload-artifact@v4
        with:
          name: msan-report-${{ github.event.repository.name}}-on-${{ matrix.os }}-from_branch_${{ github.ref_name }}
          path: './memorysan_logs/*'
